-------1.SQL

-- CREACION DE TABLAS

--Creamos la tabla alquiler.
--Entiendo que la delegacion de  entrega es obligatoria 
--indicarla, el que se pueda cambiar despues es independiente.
--Lo mismo con la fecha de  fin, aunque luego se pueda ampliar
--es obligatorio indicarla
CREATE TABLE ALQUILER(ID_ALQUILER INT NOT NULL, 
BASTIDOR VARCHAR(17) NOT NULL, 
DNI_CLIENTE VARCHAR(9) NOT NULL, 
DELEGACION_RECOGER VARCHAR(50) NOT NULL, 
DELEGACION_DEJAR VARCHAR(50) NOT NULL, 
KMS_INICIALES NUMERIC(6,0) NOT NULL, 
KMS_FINALES NUMERIC(6,0) NULL, 
FECHA_INICIO TIMESTAMP NOT NULL, 
FECHA_FIN TIMESTAMP NOT NULL, 
DESCUENTO NUMBER(6,0) DEFAULT (0));

--Creamos la tabla que contendra el acabado de un coche en particular
CREATE TABLE ACABADODEUNCOCHE (BASTIDOR VARCHAR(17) NOT NULL, 
AIRE_ACONDICIONADO VARCHAR(2) DEFAULT ('NO'), 
CLIMATIZADOR VARCHAR(2) DEFAULT ('NO'), 
NAVEGADOR VARCHAR(2) DEFAULT ('NO'), 
BLUETOOHT VARCHAR(2) DEFAULT ('NO'), 
MP3 VARCHAR(2) DEFAULT ('NO'), 
CAMBIO_AUTOMATICO VARCHAR(2) DEFAULT ('NO'), 
TECHO_SOLAR VARCHAR(2) DEFAULT ('NO'));

--Creamos la tabla coche
CREATE TABLE COCHE (BASTIDOR VARCHAR(17) NOT NULL, 
MARCA VARCHAR(25) NOT NULL, 
MODELO VARCHAR(25), 
MATRICULA VARCHAR(7) NOT NULL, 
COLOR_ACTUAL VARCHAR(15) NOT NULL, 
TIPO_CATEGORIA VARCHAR(15) NOT NULL);

--Creamos la tabla cliente. El genero no es obligatorio
CREATE TABLE CLIENTE (DNI_NIE_PASAPORTE VARCHAR(9) NOT NULL, 
NOMBRE VARCHAR(50) NOT NULL, 
APELLIDOS VARCHAR(50) NOT NULL, 
EDAD INT NOT NULL, 
GENERO VARCHAR(1) NULL);

--Creamos al tabla categoria
CREATE TABLE CATEGORIA (TIPO VARCHAR(15) NOT NULL, 
PRECIO_DIA INT NOT NULL);

-- PRIMARY KEY
--Insertamos las PK de cada tabla
ALTER TABLE ALQUILER ADD CONSTRAINT PK_ID_ALQUILER 
PRIMARY KEY (ID_ALQUILER);

ALTER TABLE ACABADODEUNCOCHE ADD CONSTRAINT PK_ACABADO_BASTIDOR 
PRIMARY KEY (BASTIDOR);

ALTER TABLE COCHE ADD CONSTRAINT PK_COCHE_BASTIDOR 
PRIMARY KEY (BASTIDOR);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_DNI_NIE_PASAPORTE 
PRIMARY KEY (DNI_NIE_PASAPORTE);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_TIPO 
PRIMARY KEY (TIPO);

-- FOREIGN KEY
--Insertamos las FK de cada tabla
ALTER TABLE COCHE ADD CONSTRAINT FK_TIPO_CATEGORIA_COCHE 
FOREIGN KEY (TIPO_CATEGORIA) REFERENCES CATEGORIA(TIPO);

ALTER TABLE ACABADODEUNCOCHE ADD CONSTRAINT FK_BASTIDOR_ACABADO 
FOREIGN KEY (BASTIDOR) REFERENCES COCHE(BASTIDOR);

ALTER TABLE ALQUILER ADD CONSTRAINT FK_BASTIDOR_ALQUILER 
FOREIGN KEY (BASTIDOR) REFERENCES COCHE(BASTIDOR);

ALTER TABLE ALQUILER ADD CONSTRAINT FK_ALQUILER_DNI_CLIENTE 
FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE (DNI_NIE_PASAPORTE);
