INSERT INTO categorias 	(nombre_cat, precio_dia) 
		VALUES 			('Functional','95')
INSERT INTO categorias	(nombre_cat, precio_dia) 
		VALUES 			('Advance','120')
INSERT INTO categorias 	(nombre_cat, precio_dia) 
		VALUES 			('Prestige','200')

INSERT INTO acabados 	(id_acabado, nombre_cat) 
		VALUES 			('01','Functional')
INSERT INTO acabados 	(id_acabado, automatico, nombre_cat) 
		VALUES 			('02','si','Prestige')
INSERT INTO acabados 	(id_acabado, navegador, bluetooth, nombre_cat) 
		VALUES 			('03','si','si','Prestige')
INSERT INTO acabados 	(id_acabado, bluetooth, nombre_cat) 
		VALUES 			('04','si','Advance')

INSERT INTO flotas 	(marca, modelo, color, matricula, bastidor, id_acabado) 
		VALUES 		('Mercedes','Clase B','Verde','1234ABC','ABCD123456','02')
INSERT INTO flotas 	(marca, modelo, color, matricula, bastidor, id_acabado) 
		VALUES 		('Renault','Fluenze','Azul','1111ABC','1234ABCDEF','03')
INSERT INTO flotas 	(marca, modelo, color, matricula, bastidor, id_acabado) 
		VALUES 		('Renault','Kangoo','Gris','4321ABC','WXYZ987654','04')
INSERT INTO flotas 	(marca, modelo, color, matricula, bastidor, id_acabado) 
		VALUES 		('Renault','Modus','Rojo','5678DEF','9876VUWYXZ','04')

INSERT INTO clientes (nombre, apellidos, genero, edad, dni_nie) 
		VALUES 		('Pedro','Martinez Martinez','Varon','43','25665420-U')
INSERT INTO clientes (nombre, apellidos, genero, edad, dni_nie) 
		VALUES 		('Juan','Perez Perez','Varon','32','49089489-R')
INSERT INTO clientes (nombre, apellidos, genero, edad, dni_nie) 
		VALUES 		('Manolo','Bombo Bombo','Varon','37','32456789-Y')

INSERT INTO alquileres 	(deleg_inicio, deleg_fin, km_inicio, km_fin, fecha_inicio, fecha_fin, bastidor, dni_nie) 
		VALUES 			('Madrid','Madrid','24500','24700',TO_DATE('01/01/12','dd/mm/yy'),TO_DATE('01/02/13','dd/mm/yy'),'ABCD123456','25665420-U')
INSERT INTO alquileres 	(deleg_inicio, deleg_fin, km_inicio, km_fin, fecha_inicio, fecha_fin, bastidor, dni_nie) 
		VALUES 			('Madrid','Toledo','15200','15300',TO_DATE('01/03/12','dd/mm/yy'),TO_DATE('01/04/13','dd/mm/yy'),'1234ABCDEF','25665420-U')
INSERT INTO alquileres 	(deleg_inicio, deleg_fin, km_inicio, km_fin, fecha_inicio, fecha_fin, descuento, bastidor, dni_nie) 
		VALUES 			('Madrid','Sevilla','29500','3100',TO_DATE('01/03/12','dd/mm/yy'),TO_DATE('01/04/13','dd/mm/yy'),'5%','WXYZ987654','49089489-R')
INSERT INTO alquileres 	(deleg_inicio, km_inicio, fecha_inicio, bastidor, dni_nie) 
		VALUES 			('Barcelona','24500',TO_DATE('01/03/13','dd/mm/yy'),'9876VUWYXZ','32456789-Y')
;