
* RESPONDE A CADA PREGUNTA CON UNA SOLA SENTENCIA SQL

** Nota media
select avg(numeric_grade)
from grade
** Nota media de los exámenes finales
select avg(numeric_grade)
from grade
where grade_type_code='FI';
** Número de alumnos totales
select count(*)
from student;
** Número de alumnos con tratamiento 'Ms'
select count(*)
from student
where salutation='Ms.'
** Número de alumnos con tratamiento 'Ms' o 'Mr'

select count(*)
from student
where salutation in( 'Ms.', 'Mr.');
** ¿Cuáles son las descripciones de los tipos de notas que se pueden poner?
select grade_type_code, description from GRADE_TYPE;

** Alumnos cuyo nombre comience por 'o' (mayúscula o minúscula)
select * from student
where lower(first_name) like 'o%';

** Alumnos con un nombre de 4 letras
select * from student
where first_name like '____';


** ¿Cuál es la mejor nota en la sección con identificador 86?

** ¿Cuál es la mejor nota del alumno con identificador 102?

** ¿Cuál es el identificador del alumno con la mejor nota en la sección con identificador 86?

** ¿En qué fecha comienza la sección que primero empieza sus clases?
select min(start_date_time) from section;

** Datos de la sección que empieza la última
select * 
from section
where start_date_time=(
  select max(start_date_time) from section
);


** ¿En qué fecha comienza la última sección?
select max(start_date_time) from section;

** Lista de alumnos ordenados por apellido (sin importar minúsculas)
select first_name,last_name,student_id, lower(last_name) as paraordenar 
from student
order by paraordenar;

** Lista de apellidos de alumnos, y cuántos alumnos tienen cada apellido
select count(*) as cuantos, last_name
from student
group by last_name
order by cuantos desc;

** Lista de apellidos de alumnos, y la fecha del primer registro de un alumno con ese apellido
select count(*), last_name, min(registration_date)
from student
group by last_name
order by last_name;

select last_name, registration_date
from student studentdefuera
where registration_date = (
  select min(registration_date)
  from student studentdedentro
  where studentdedentro.last_name=studentdefuera.last_name
)
order by last_name;

** ¿Qué aulas (location) se usan por las secciones?

** ¿Cuántas aulas (location) se usan por las secciones?

** ¿Cuál es el identificador del alumno con la peor nota en la sección con identificador 86?

** ¿Cuál es el identificador del alumno con la mejor nota de proyecto (PJ) en la sección con identificador 86?

** ¿Cuál es la media de las notas de proyecto (PJ) en la sección con identificador 86?

** ¿Cuántos alumnos hay matriculados en la sección con identificador 86?

** ¿Cuántas secciones hay?

** ¿Cuál es la media de capacidad de las secciones?

** ¿Cuál es la media de capacidad de las aulas (location)?


** ¿Cuál es el máximo de alumnos matriculable (suma de capacidades de las secciones)?
** ¿Cuáles son las aulas (location) en las que se imparten secciones con más de 20 alumnos?
select distinct location from section
where capacity>20;

** ¿Cuáles son las aulas (location) en las que se imparten secciones con menos de 15 alumnos?

** ¿Qué nota alfabética consigo con un 72 numérico?

select letter_grade from GRADE_CONVERSION
where 72 >= min_grade and 72 <=max_grade;

select letter_grade from GRADE_CONVERSION
where 72 between min_grade and max_grade;

** ¿Qué nota alfabética consigo con un 74 numérico?

select letter_grade from GRADE_CONVERSION
where 74 between min_grade and max_grade;

** ¿Qué rango de nota numérica puede tener un alumno que ha conseguido un B+?
select min_grade, max_grade from GRADE_CONVERSION
where letter_grade='B+';


** ¿Cuántos códigos postales hay en la ciudad de New York?


select count(*) from zipcode where city='New York';
** ¿Cuántos códigos postales hay en el estado de New York (NY)?
select count(*) from zipcode where state='NY';

** ¿Cuántos estados hay registrados en la base de datos?
select count(state)
from (
  select state from zipcode
  group by state
);

select count(distinct state)
from zipcode;

** ¿Cuántos alumnos varones hay? (los reverendos son varones)

** ¿Cuántas alumnas hay? (los doctores son mujeres)

** ¿Cuáles son las descripciones de los cursos que necesitan un curso previo?

select * from course where not(prerequisite is null);






