----- 2.sql


-- 2. Datos a insertar
--  Se insertarán los siguientes datos en las tablas.
--  Los campos no incluidos se rellenarán a gusto del alumno:
--  - Pedro Martínez Martínez alquiló un Mercedes Clase B verde 
--    con Matrícula 1234ABC el 1-1-12 al 1-2-13.
--    Tenía cambio automático, y realizó 200 km.
--  - Pedro Martínez Martínez alquiló un Renault Fluenze
--    con Matrícula 1111ABC el 1-3-12 al 1-4-13. 
--    Tenía navegador y bluetooth, y realizó 100 km.
--  - Los precios por día de las categorías Functional, Advance y Prestige 
--    son de 200€, 120€ y 95€, respectivamente.
--  - Los coches con cambio automático o navegador se están clasificando 
--    como categoría Prestige. Los que tienen bluetooth, en la categoría Advance.
--  - Juan Pérez Pérez alquiló un Renault Kangoo con Matrícula 4321ABC el 1-3-12 al 1-4-13.
--    Tenía bluetooth, y se le aplicó un descuento del 5%.
--    Recogió el coche en Madrid, y lo devolvió en Sevilla
--  - Manolo Bombo Bombo alquiló un Renault Modus el 1-3-13, 
--    y aún no lo ha devuelto. Tenía bluetooth, y lo recogió en Brcelona.



-- INSERTO DATOS EN LA TABLA CLIENTE

INSERT INTO CLIENTE (DNI_NIE_PASAPORTE, NOMBRE, APELLIDOS, EDAD, GENERO)
VALUES ('12345678P', 'PEDRO', 'MARTINEZ MARTINEZ', 18, 'H');

INSERT INTO CLIENTE VALUES ('12345678J','JUAN','PEREZ PEREZ',32,'H');

INSERT INTO CLIENTE VALUES ('12345678M','MANOLO','BOMBO BOMBO',65,'H');


-- INSERTO DATOS EN LA TABLA CATEGORIA

INSERT INTO CATEGORIA (ID_CATEGORIA, TIPO_CATEGORIA, PRECIO_DIA)
VALUES (101, 'FUNCTIONAL', 200);

INSERT INTO CATEGORIA
VALUES (102, 'ADVANCE', 120);

INSERT INTO CATEGORIA
VALUES (103, 'PRESTIGE', 95);


-- INSERTO DATOS EN LA TABLA ACABADOS

INSERT INTO ACABADO (ID_ACABADO, AIRE_ACONDICIONADO, 
CLIMATIZADOR, NAVEGADOR, BLUETOOHT, MP3, 
CAMBIO_AUTOMATICO, TECHO_SOLAR)
VALUES (1001,'NO','NO','NO','NO','NO','SI','NO');

INSERT INTO ACABADO (ID_ACABADO, NAVEGADOR, BLUETOOHT)
VALUES (1002,'SI','SI');

INSERT INTO ACABADO (ID_ACABADO, BLUETOOHT)
VALUES (1003,'SI');


-- INSERTO DATOS EN LA TABLA COCHE

INSERT INTO COCHE (BASTIDOR, MARCA, MODELO, MATRICULA, 
COLOR_ORIGINAL, ID_CAT, ACABADO)
VALUES ('ABCDEFGH100000001','MERCEDES','CLASE B',
'1234ABC','ROJO',103,1001);

INSERT INTO COCHE
VALUES ('ABCDEFGH100000002','RENAULT','FLUENZE',
'1111ABC','PLATA',103,1002);

INSERT INTO COCHE
VALUES ('ABCDEFGH100000003','RENAULT','KANGOO',
'4321ABC','AZUL',102,1003);

INSERT INTO COCHE
VALUES ('ABCDEFGH100000004','RENAULT','MODUS',
'2222ABC','NEGRO',102,1003);


-- INSERTO DATOS EN LA TABLA ALQUILER

-- ALQUILER1 PEDRO MARTINEZ MARTINEZ

INSERT INTO ALQUILER (ID_ALQUILER, NUM_BASTIDOR, DNI_CLIENTE, 
DELEGACION_RECOGER, DELEGACION_DEJAR, KMS_INICIALES, 
KMS_FINALES, FECHA_INICIO, FECHA_FIN)
VALUES (10001,'ABCDEFGH100000001','12345678P',
'MADRID','BARCELONA',25000,25200,
TO_DATE('01/01/2012','DD/MM/YYYY'),TO_DATE('01/02/2013','DD/MM/YYYY'));


-- ALQUILER2 PEDRO MARTINEZ MARTINEZ

INSERT INTO ALQUILER (ID_ALQUILER, NUM_BASTIDOR, DNI_CLIENTE, 
DELEGACION_RECOGER, DELEGACION_DEJAR, KMS_INICIALES, 
KMS_FINALES, FECHA_INICIO, FECHA_FIN)
VALUES (10002,'ABCDEFGH100000002','12345678P',
'BARCELONA','MADRID',26000,26100,
TO_DATE('01/03/2012','DD/MM/YYYY'),TO_DATE('01/04/2013','DD/MM/YYYY'));


-- ALQUILER JUAN PEREZ PEREZ

INSERT INTO ALQUILER
VALUES (10003,'ABCDEFGH100000003','12345678J',
'MADID','SEVILLA',37000,37600,
TO_DATE('01/03/2012','DD/MM/YYYY'),TO_DATE('01/04/2013','DD/MM/YYYY'),5);


-- ALQUILER MANOLO BOMBO BOMBO

INSERT INTO ALQUILER (ID_ALQUILER, NUM_BASTIDOR, DNI_CLIENTE, 
DELEGACION_RECOGER, DELEGACION_DEJAR, KMS_INICIALES, FECHA_INICIO)
VALUES (10004,'ABCDEFGH100000004','12345678M',
'BACELONA','BILBAO',8000, TO_DATE('01/03/2012','DD/MM/YYYY'));