----- 3.sql


-- 3. Modificación del problema
--  - La empresa se ha dado cuenta que necesita realizar 
--    revisiones periódicas a los coches. 
--    Necesita saber, por cada coche:
--    · Tipos de revisiones a realizar (ITV, mantenimiento)
--    · Nº de kilómetros o fecha máxima para esa revisión
--    · Nº de kilómetros o fecha en la que se pasaron las anteriores revisiones.
--  - Algunos coches se han repintado de otros colores. 
--    Se necesita saber qué colores ha tenido un coche, en qué fechas.
--  - Se desa añadir un acacbado para asientos calefactados.


CREATE TABLE REPINTADO(
ID_REPINTADO INT NOT NULL,
N_BASTIDOR VARCHAR(17) NOT NULL,
REPINTADO VARCHAR(15) NOT NULL,
FECHA_REPINTADO DATE NOT NULL,
CONSTRAINT PK_IDREPINTADO PRIMARY KEY (ID_REPINTADO),
CONSTRAINT FK_NBASTIDOR
FOREIGN KEY (N_BASTIDOR) REFERENCES COCHE (BASTIDOR),
CONSTRAINT UQ_BASTI_REPIN_FECHA 
UNIQUE (N_BASTIDOR, REPINTADO, FECHA_REPINTADO)
);

CREATE TABLE REVISION_MANTENIMIENTO(
ID_REVI_MAN INT NOT NULL,
NU_BASTIDOR VARCHAR(17) NOT NULL,
FECHA_REV_MAN DATE NOT NULL,
KMS_REV_MAN INT NOT NULL,
CONSTRAINT PK_IDREVIMAN PRIMARY KEY (ID_REVI_MAN),
CONSTRAINT FK_NUBASTIDOR
FOREIGN KEY (NU_BASTIDOR) REFERENCES COCHE (BASTIDOR),
CONSTRAINT UQ_BASTI_FECHA_KMS_REVI_MANTE 
UNIQUE (NU_BASTIDOR, FECHA_REV_MAN, KMS_REV_MAN)
);

CREATE TABLE REVISION_ITV(
ID_REVI_ITV INT NOT NULL,
NUME_BASTIDOR VARCHAR(17) NOT NULL,
FECHA_REV_ITV DATE NOT NULL,
CONSTRAINT PK_IDREVIITV PRIMARY KEY (ID_REVI_ITV),
CONSTRAINT FK_NUMEBASTIDOR
FOREIGN KEY (NUME_BASTIDOR) REFERENCES COCHE (BASTIDOR),
CONSTRAINT UQ_BASTI_FECHA_REVI_ITV
UNIQUE (NUME_BASTIDOR, FECHA_REV_ITV)
);


-- INSERTAR COLUMNA ASIENTOS_CALEFACTADOS EN TABLA ACABADO

ALTER TABLE ACABADO ADD
ASIENTOS_CALEFACTADOS VARCHAR(2) DEFAULT ('NO') 
CHECK (ASIENTOS_CALEFACTADOS IN ('NO','SI'));